AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
    - '**/config.ru'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.rb'
    - '**/*.spec'

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/Documentation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/ExtraSpacing:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/PredicateName:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpaceAroundOperators:
  MultiSpaceAllowedForOperators:
    - '='
    - '=>'
    - '||'
    - '||='
    - '+='
    - 'and'
    - '+'
    - '&&'

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyleForEmptyBraces: space

Style/SpaceInsideParens:
  Enabled: false
